### PR TITLE
3.0.0-RC2: Scala-js and SuperSafe

### PR DESCRIPTION
**Pull request by cheeseng**
Updated installation guide to include scala-js and SuperSafe correctly.

### CODE REVIEW

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by cheeseng** [comment]
@cla-bot[bot] check

**Comment by artimasites** [comment]
@cla-bot[bot] check

**Comment by bvenners** [comment]
@cheeseng Is this PR still relevant? If not, please close it. Else answer here and I'll merge. Tnx.

**Comment by cheeseng** [comment]
@bvenners Closing as this is superseded by https://github.com/scalatest/scalatest-website/pull/182 .

**Pull request closed without merging**
