### PR TITLE
fix doc about minSuccessful default

### PR DESCRIPTION
**Pull request by nevillelyh**
This fixes scalatest/scalatest#1090

### CODE REVIEW

**Comment by plinlor** [comment]
@cla-bot[bot] check

**Review by magdzikk — APPROVED** [review]
Is there anything we can do to get this merged? The docs are still confusing about this.

**Comment by bvenners** [comment]
@magdzikk I'll get it merged soon. It will go into 3.1.x-new.

**Comment by magdzikk** [comment]
Great news, thanks @bvenners :)

**Pull request merged**
